In [40]:
import numpy as np

# LU decomposition with partial pivoting

# Matrix A
a = np.array([[2, 1, 5], [4, 4, -4], [1, 3, 1]], dtype=float)

# Uncomment one of the following if desired:
# a = np.array([[1, 2, -1], [2, 1, -2], [-3, 1, 1]], dtype=float)
# a = np.array([[10, -7, 0], [-3, 2, 6], [5, -1, 5]], dtype=float)

#A = a.copy()

# Right-hand side vector
b = np.array([3, 3, -6])

# Initialize L
L = np.eye(3)

n = a.shape[0] # size of the first dimension

# LU decomposition with partial pivoting
for j in range(n - 1):

    # Find pivot row
    I = j + np.argmax(np.abs(a[j:n, j]))

    # Row swapping for partial pivoting
    if I != j:
        a[[j, I], :] = a[[I, j], :]

    # Gaussian elimination
    for i in range(j + 1, n):
        mult = a[i, j] / a[j, j] # multiplying factor for elimination 
        a[i, j] = mult  #storing the multiplying factor in the lower triangle
        for k in range(j + 1, n):
            a[i, k] = a[i, k] - mult * a[j, k]
        
# Extract L and U
U = np.zeros((3,3))

for i in range(n):
    for j in range(n):
        if i > j:
            L[i, j] = a[i, j]
        else:
            U[i, j] = a[i, j]

c=np.dot(np.linalg.inv(L),b)
x=np.dot(np.linalg.inv(U),c)

print("L =")
print(L)

print("\nU =")
print(U)

print("\n x=")
print(x)


L =
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.5   1.  ]]

U =
[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]

 x=
[-1.96875   1.921875 -0.796875]


In [4]:
a.shape[0

3